//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace R_9015_evtRetCons_v2_01_01_A {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01", IsNullable=false)]
    public partial class Reinf {
        
        private ReinfEvtRetCons evtRetConsField;
        
        private SignatureType signatureField;
        
        /// <remarks/>
        public ReinfEvtRetCons evtRetCons {
            get {
                return this.evtRetConsField;
            }
            set {
                this.evtRetConsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetCons {
        
        private ReinfEvtRetConsIdeEvento ideEventoField;
        
        private ReinfEvtRetConsIdeContri ideContriField;
        
        private ReinfEvtRetConsIdeRecRetorno ideRecRetornoField;
        
        private ReinfEvtRetConsInfoRecEv infoRecEvField;
        
        private ReinfEvtRetConsInfoCR_CNR infoCR_CNRField;
        
        private ReinfEvtRetConsInfoTotalCR infoTotalCRField;
        
        private string idField;
        
        /// <remarks/>
        public ReinfEvtRetConsIdeEvento ideEvento {
            get {
                return this.ideEventoField;
            }
            set {
                this.ideEventoField = value;
            }
        }
        
        /// <remarks/>
        public ReinfEvtRetConsIdeContri ideContri {
            get {
                return this.ideContriField;
            }
            set {
                this.ideContriField = value;
            }
        }
        
        /// <remarks/>
        public ReinfEvtRetConsIdeRecRetorno ideRecRetorno {
            get {
                return this.ideRecRetornoField;
            }
            set {
                this.ideRecRetornoField = value;
            }
        }
        
        /// <remarks/>
        public ReinfEvtRetConsInfoRecEv infoRecEv {
            get {
                return this.infoRecEvField;
            }
            set {
                this.infoRecEvField = value;
            }
        }
        
        /// <remarks/>
        public ReinfEvtRetConsInfoCR_CNR infoCR_CNR {
            get {
                return this.infoCR_CNRField;
            }
            set {
                this.infoCR_CNRField = value;
            }
        }
        
        /// <remarks/>
        public ReinfEvtRetConsInfoTotalCR infoTotalCR {
            get {
                return this.infoTotalCRField;
            }
            set {
                this.infoTotalCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsIdeEvento {
        
        private string perApurField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
        public string perApur {
            get {
                return this.perApurField;
            }
            set {
                this.perApurField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Object", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class ObjectType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string idField;
        
        private string mimeTypeField;
        
        private string encodingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SPKIData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SPKIDataType {
        
        private byte[][] sPKISexpField;
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType="base64Binary")]
        public byte[][] SPKISexp {
            get {
                return this.sPKISexpField;
            }
            set {
                this.sPKISexpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("PGPData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class PGPDataType {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        PGPKeyID,
        
        /// <remarks/>
        PGPKeyPacket,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType {
        
        private string x509IssuerNameField;
        
        private string x509SerialNumberField;
        
        /// <remarks/>
        public string X509IssuerName {
            get {
                return this.x509IssuerNameField;
            }
            set {
                this.x509IssuerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string X509SerialNumber {
            get {
                return this.x509SerialNumberField;
            }
            set {
                this.x509SerialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class X509DataType {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType))]
        [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        X509CRL,
        
        /// <remarks/>
        X509Certificate,
        
        /// <remarks/>
        X509IssuerSerial,
        
        /// <remarks/>
        X509SKI,
        
        /// <remarks/>
        X509SubjectName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class RetrievalMethodType {
        
        private TransformType[] transformsField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Transform", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class TransformType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class RSAKeyValueType {
        
        private byte[] modulusField;
        
        private byte[] exponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Modulus {
            get {
                return this.modulusField;
            }
            set {
                this.modulusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Exponent {
            get {
                return this.exponentField;
            }
            set {
                this.exponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class DSAKeyValueType {
        
        private byte[] pField;
        
        private byte[] qField;
        
        private byte[] gField;
        
        private byte[] yField;
        
        private byte[] jField;
        
        private byte[] seedField;
        
        private byte[] pgenCounterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PgenCounter {
            get {
                return this.pgenCounterField;
            }
            set {
                this.pgenCounterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("KeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class KeyValueType {
        
        private object itemField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("KeyInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class KeyInfoType {
        
        private object[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        private string[] textField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType))]
        [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType))]
        [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType))]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        KeyName,
        
        /// <remarks/>
        KeyValue,
        
        /// <remarks/>
        MgmtData,
        
        /// <remarks/>
        PGPData,
        
        /// <remarks/>
        RetrievalMethod,
        
        /// <remarks/>
        SPKIData,
        
        /// <remarks/>
        X509Data,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureValueType {
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("DigestMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class DigestMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class ReferenceType {
        
        private TransformType[] transformsField;
        
        private DigestMethodType digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public DigestMethodType DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureMethodType {
        
        private string hMACOutputLengthField;
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string HMACOutputLength {
            get {
                return this.hMACOutputLengthField;
            }
            set {
                this.hMACOutputLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class CanonicalizationMethodType {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignedInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignedInfoType {
        
        private CanonicalizationMethodType canonicalizationMethodField;
        
        private SignatureMethodType signatureMethodField;
        
        private ReferenceType[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        public CanonicalizationMethodType CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SignatureMethodType SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ReferenceType[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureType {
        
        private SignedInfoType signedInfoField;
        
        private SignatureValueType signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private ObjectType[] objectField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        public SignatureValueType SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object")]
        public ObjectType[] Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsIdeContri {
        
        private byte tpInscField;
        
        private string nrInscField;
        
        /// <remarks/>
        public byte tpInsc {
            get {
                return this.tpInscField;
            }
            set {
                this.tpInscField = value;
            }
        }
        
        /// <remarks/>
        public string nrInsc {
            get {
                return this.nrInscField;
            }
            set {
                this.nrInscField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsIdeRecRetorno {
        
        private ReinfEvtRetConsIdeRecRetornoIdeStatus ideStatusField;
        
        /// <remarks/>
        public ReinfEvtRetConsIdeRecRetornoIdeStatus ideStatus {
            get {
                return this.ideStatusField;
            }
            set {
                this.ideStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsIdeRecRetornoIdeStatus {
        
        private byte cdRetornoField;
        
        private string descRetornoField;
        
        private ReinfEvtRetConsIdeRecRetornoIdeStatusRegOcorrs[] regOcorrsField;
        
        /// <remarks/>
        public byte cdRetorno {
            get {
                return this.cdRetornoField;
            }
            set {
                this.cdRetornoField = value;
            }
        }
        
        /// <remarks/>
        public string descRetorno {
            get {
                return this.descRetornoField;
            }
            set {
                this.descRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regOcorrs")]
        public ReinfEvtRetConsIdeRecRetornoIdeStatusRegOcorrs[] regOcorrs {
            get {
                return this.regOcorrsField;
            }
            set {
                this.regOcorrsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsIdeRecRetornoIdeStatusRegOcorrs {
        
        private byte tpOcorrField;
        
        private string localErroAvisoField;
        
        private string codRespField;
        
        private string dscRespField;
        
        /// <remarks/>
        public byte tpOcorr {
            get {
                return this.tpOcorrField;
            }
            set {
                this.tpOcorrField = value;
            }
        }
        
        /// <remarks/>
        public string localErroAviso {
            get {
                return this.localErroAvisoField;
            }
            set {
                this.localErroAvisoField = value;
            }
        }
        
        /// <remarks/>
        public string codResp {
            get {
                return this.codRespField;
            }
            set {
                this.codRespField = value;
            }
        }
        
        /// <remarks/>
        public string dscResp {
            get {
                return this.dscRespField;
            }
            set {
                this.dscRespField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoRecEv {
        
        private string nrProtLoteField;
        
        private System.DateTime dhProcessField;
        
        private string tpEvField;
        
        private string idEvField;
        
        private string hashField;
        
        /// <remarks/>
        public string nrProtLote {
            get {
                return this.nrProtLoteField;
            }
            set {
                this.nrProtLoteField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dhProcess {
            get {
                return this.dhProcessField;
            }
            set {
                this.dhProcessField = value;
            }
        }
        
        /// <remarks/>
        public string tpEv {
            get {
                return this.tpEvField;
            }
            set {
                this.tpEvField = value;
            }
        }
        
        /// <remarks/>
        public string idEv {
            get {
                return this.idEvField;
            }
            set {
                this.idEvField = value;
            }
        }
        
        /// <remarks/>
        public string hash {
            get {
                return this.hashField;
            }
            set {
                this.hashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoCR_CNR {
        
        private string nrRecArqBaseField;
        
        private byte indExistInfoField;
        
        private string identEscritDCTFField;
        
        private ReinfEvtRetConsInfoCR_CNRTotApurMen[] totApurMenField;
        
        private ReinfEvtRetConsInfoCR_CNRTotApurQui[] totApurQuiField;
        
        private ReinfEvtRetConsInfoCR_CNRTotApurDec[] totApurDecField;
        
        private ReinfEvtRetConsInfoCR_CNRTotApurSem[] totApurSemField;
        
        private ReinfEvtRetConsInfoCR_CNRTotApurDia[] totApurDiaField;
        
        /// <remarks/>
        public string nrRecArqBase {
            get {
                return this.nrRecArqBaseField;
            }
            set {
                this.nrRecArqBaseField = value;
            }
        }
        
        /// <remarks/>
        public byte indExistInfo {
            get {
                return this.indExistInfoField;
            }
            set {
                this.indExistInfoField = value;
            }
        }
        
        /// <remarks/>
        public string identEscritDCTF {
            get {
                return this.identEscritDCTFField;
            }
            set {
                this.identEscritDCTFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurMen")]
        public ReinfEvtRetConsInfoCR_CNRTotApurMen[] totApurMen {
            get {
                return this.totApurMenField;
            }
            set {
                this.totApurMenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurQui")]
        public ReinfEvtRetConsInfoCR_CNRTotApurQui[] totApurQui {
            get {
                return this.totApurQuiField;
            }
            set {
                this.totApurQuiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurDec")]
        public ReinfEvtRetConsInfoCR_CNRTotApurDec[] totApurDec {
            get {
                return this.totApurDecField;
            }
            set {
                this.totApurDecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurSem")]
        public ReinfEvtRetConsInfoCR_CNRTotApurSem[] totApurSem {
            get {
                return this.totApurSemField;
            }
            set {
                this.totApurSemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurDia")]
        public ReinfEvtRetConsInfoCR_CNRTotApurDia[] totApurDia {
            get {
                return this.totApurDiaField;
            }
            set {
                this.totApurDiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoCR_CNRTotApurMen {
        
        private string cRMenField;
        
        private string vlrCRMenInfField;
        
        private string vlrCRMenCalcField;
        
        private string vlrCRMenDCTFField;
        
        private string vlrCRMenSuspInfField;
        
        private string vlrCRMenSuspCalcField;
        
        private string vlrCRMenSuspDCTFField;
        
        private string natRendField;
        
        /// <remarks/>
        public string CRMen {
            get {
                return this.cRMenField;
            }
            set {
                this.cRMenField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenInf {
            get {
                return this.vlrCRMenInfField;
            }
            set {
                this.vlrCRMenInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenCalc {
            get {
                return this.vlrCRMenCalcField;
            }
            set {
                this.vlrCRMenCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenDCTF {
            get {
                return this.vlrCRMenDCTFField;
            }
            set {
                this.vlrCRMenDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenSuspInf {
            get {
                return this.vlrCRMenSuspInfField;
            }
            set {
                this.vlrCRMenSuspInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenSuspCalc {
            get {
                return this.vlrCRMenSuspCalcField;
            }
            set {
                this.vlrCRMenSuspCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenSuspDCTF {
            get {
                return this.vlrCRMenSuspDCTFField;
            }
            set {
                this.vlrCRMenSuspDCTFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string natRend {
            get {
                return this.natRendField;
            }
            set {
                this.natRendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoCR_CNRTotApurQui {
        
        private byte perApurQuiField;
        
        private string cRQuiField;
        
        private string vlrCRQuiInfField;
        
        private string vlrCRQuiCalcField;
        
        private string vlrCRQuiDCTFField;
        
        private string vlrCRQuiSuspInfField;
        
        private string vlrCRQuisSuspCalcField;
        
        private string vlrCRQuiSuspDCTFField;
        
        private string natRendField;
        
        /// <remarks/>
        public byte perApurQui {
            get {
                return this.perApurQuiField;
            }
            set {
                this.perApurQuiField = value;
            }
        }
        
        /// <remarks/>
        public string CRQui {
            get {
                return this.cRQuiField;
            }
            set {
                this.cRQuiField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuiInf {
            get {
                return this.vlrCRQuiInfField;
            }
            set {
                this.vlrCRQuiInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuiCalc {
            get {
                return this.vlrCRQuiCalcField;
            }
            set {
                this.vlrCRQuiCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuiDCTF {
            get {
                return this.vlrCRQuiDCTFField;
            }
            set {
                this.vlrCRQuiDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuiSuspInf {
            get {
                return this.vlrCRQuiSuspInfField;
            }
            set {
                this.vlrCRQuiSuspInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuisSuspCalc {
            get {
                return this.vlrCRQuisSuspCalcField;
            }
            set {
                this.vlrCRQuisSuspCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuiSuspDCTF {
            get {
                return this.vlrCRQuiSuspDCTFField;
            }
            set {
                this.vlrCRQuiSuspDCTFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string natRend {
            get {
                return this.natRendField;
            }
            set {
                this.natRendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoCR_CNRTotApurDec {
        
        private byte perApurDecField;
        
        private string cRDecField;
        
        private string vlrCRDecInfField;
        
        private string vlrCRDecCalcField;
        
        private string vlrCRDecDCTFField;
        
        private string vlrCRDecSuspInfField;
        
        private string vlrCRDecSuspCalcField;
        
        private string vlrCRDecSuspDCTFField;
        
        private string natRendField;
        
        /// <remarks/>
        public byte perApurDec {
            get {
                return this.perApurDecField;
            }
            set {
                this.perApurDecField = value;
            }
        }
        
        /// <remarks/>
        public string CRDec {
            get {
                return this.cRDecField;
            }
            set {
                this.cRDecField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecInf {
            get {
                return this.vlrCRDecInfField;
            }
            set {
                this.vlrCRDecInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecCalc {
            get {
                return this.vlrCRDecCalcField;
            }
            set {
                this.vlrCRDecCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecDCTF {
            get {
                return this.vlrCRDecDCTFField;
            }
            set {
                this.vlrCRDecDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecSuspInf {
            get {
                return this.vlrCRDecSuspInfField;
            }
            set {
                this.vlrCRDecSuspInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecSuspCalc {
            get {
                return this.vlrCRDecSuspCalcField;
            }
            set {
                this.vlrCRDecSuspCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecSuspDCTF {
            get {
                return this.vlrCRDecSuspDCTFField;
            }
            set {
                this.vlrCRDecSuspDCTFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string natRend {
            get {
                return this.natRendField;
            }
            set {
                this.natRendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoCR_CNRTotApurSem {
        
        private byte perApurSemField;
        
        private string cRSemField;
        
        private string vlrCRSemInfField;
        
        private string vlrCRSemCalcField;
        
        private string vlrCRSemDCTFField;
        
        private string vlrCRSemSuspInfField;
        
        private string vlrCRSemSuspCalcField;
        
        private string vlrCRSemSuspDCTFField;
        
        private string natRendField;
        
        /// <remarks/>
        public byte perApurSem {
            get {
                return this.perApurSemField;
            }
            set {
                this.perApurSemField = value;
            }
        }
        
        /// <remarks/>
        public string CRSem {
            get {
                return this.cRSemField;
            }
            set {
                this.cRSemField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemInf {
            get {
                return this.vlrCRSemInfField;
            }
            set {
                this.vlrCRSemInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemCalc {
            get {
                return this.vlrCRSemCalcField;
            }
            set {
                this.vlrCRSemCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemDCTF {
            get {
                return this.vlrCRSemDCTFField;
            }
            set {
                this.vlrCRSemDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemSuspInf {
            get {
                return this.vlrCRSemSuspInfField;
            }
            set {
                this.vlrCRSemSuspInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemSuspCalc {
            get {
                return this.vlrCRSemSuspCalcField;
            }
            set {
                this.vlrCRSemSuspCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemSuspDCTF {
            get {
                return this.vlrCRSemSuspDCTFField;
            }
            set {
                this.vlrCRSemSuspDCTFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string natRend {
            get {
                return this.natRendField;
            }
            set {
                this.natRendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoCR_CNRTotApurDia {
        
        private sbyte perApurDiaField;
        
        private string cRDiaField;
        
        private string vlrCRDiaInfField;
        
        private string vlrCRDiaCalcField;
        
        private string vlrCRDiaDCTFField;
        
        private string vlrCRDiaSuspInfField;
        
        private string vlrCRDiaSuspCalcField;
        
        private string vlrCRDiaSuspDCTFField;
        
        private string natRendField;
        
        /// <remarks/>
        public sbyte perApurDia {
            get {
                return this.perApurDiaField;
            }
            set {
                this.perApurDiaField = value;
            }
        }
        
        /// <remarks/>
        public string CRDia {
            get {
                return this.cRDiaField;
            }
            set {
                this.cRDiaField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaInf {
            get {
                return this.vlrCRDiaInfField;
            }
            set {
                this.vlrCRDiaInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaCalc {
            get {
                return this.vlrCRDiaCalcField;
            }
            set {
                this.vlrCRDiaCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaDCTF {
            get {
                return this.vlrCRDiaDCTFField;
            }
            set {
                this.vlrCRDiaDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaSuspInf {
            get {
                return this.vlrCRDiaSuspInfField;
            }
            set {
                this.vlrCRDiaSuspInfField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaSuspCalc {
            get {
                return this.vlrCRDiaSuspCalcField;
            }
            set {
                this.vlrCRDiaSuspCalcField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaSuspDCTF {
            get {
                return this.vlrCRDiaSuspDCTFField;
            }
            set {
                this.vlrCRDiaSuspDCTFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string natRend {
            get {
                return this.natRendField;
            }
            set {
                this.natRendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoTotalCR {
        
        private ReinfEvtRetConsInfoTotalCRTotApurMen[] totApurMenField;
        
        private ReinfEvtRetConsInfoTotalCRTotApurQui[] totApurQuiField;
        
        private ReinfEvtRetConsInfoTotalCRTotApurDec[] totApurDecField;
        
        private ReinfEvtRetConsInfoTotalCRTotApurSem[] totApurSemField;
        
        private ReinfEvtRetConsInfoTotalCRTotApurDia[] totApurDiaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurMen")]
        public ReinfEvtRetConsInfoTotalCRTotApurMen[] totApurMen {
            get {
                return this.totApurMenField;
            }
            set {
                this.totApurMenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurQui")]
        public ReinfEvtRetConsInfoTotalCRTotApurQui[] totApurQui {
            get {
                return this.totApurQuiField;
            }
            set {
                this.totApurQuiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurDec")]
        public ReinfEvtRetConsInfoTotalCRTotApurDec[] totApurDec {
            get {
                return this.totApurDecField;
            }
            set {
                this.totApurDecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurSem")]
        public ReinfEvtRetConsInfoTotalCRTotApurSem[] totApurSem {
            get {
                return this.totApurSemField;
            }
            set {
                this.totApurSemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totApurDia")]
        public ReinfEvtRetConsInfoTotalCRTotApurDia[] totApurDia {
            get {
                return this.totApurDiaField;
            }
            set {
                this.totApurDiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoTotalCRTotApurMen {
        
        private string cRMenField;
        
        private string vlrCRMenDCTFField;
        
        private string vlrCRMenSuspDCTFField;
        
        /// <remarks/>
        public string CRMen {
            get {
                return this.cRMenField;
            }
            set {
                this.cRMenField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenDCTF {
            get {
                return this.vlrCRMenDCTFField;
            }
            set {
                this.vlrCRMenDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRMenSuspDCTF {
            get {
                return this.vlrCRMenSuspDCTFField;
            }
            set {
                this.vlrCRMenSuspDCTFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoTotalCRTotApurQui {
        
        private byte perApurQuiField;
        
        private string cRQuiField;
        
        private string vlrCRQuiDCTFField;
        
        private string vlrCRQuiSuspDCTFField;
        
        /// <remarks/>
        public byte perApurQui {
            get {
                return this.perApurQuiField;
            }
            set {
                this.perApurQuiField = value;
            }
        }
        
        /// <remarks/>
        public string CRQui {
            get {
                return this.cRQuiField;
            }
            set {
                this.cRQuiField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuiDCTF {
            get {
                return this.vlrCRQuiDCTFField;
            }
            set {
                this.vlrCRQuiDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRQuiSuspDCTF {
            get {
                return this.vlrCRQuiSuspDCTFField;
            }
            set {
                this.vlrCRQuiSuspDCTFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoTotalCRTotApurDec {
        
        private byte perApurDecField;
        
        private string cRDecField;
        
        private string vlrCRDecDCTFField;
        
        private string vlrCRDecSuspDCTFField;
        
        /// <remarks/>
        public byte perApurDec {
            get {
                return this.perApurDecField;
            }
            set {
                this.perApurDecField = value;
            }
        }
        
        /// <remarks/>
        public string CRDec {
            get {
                return this.cRDecField;
            }
            set {
                this.cRDecField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecDCTF {
            get {
                return this.vlrCRDecDCTFField;
            }
            set {
                this.vlrCRDecDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDecSuspDCTF {
            get {
                return this.vlrCRDecSuspDCTFField;
            }
            set {
                this.vlrCRDecSuspDCTFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoTotalCRTotApurSem {
        
        private byte perApurSemField;
        
        private string cRSemField;
        
        private string vlrCRSemDCTFField;
        
        private string vlrCRSemSuspDCTFField;
        
        /// <remarks/>
        public byte perApurSem {
            get {
                return this.perApurSemField;
            }
            set {
                this.perApurSemField = value;
            }
        }
        
        /// <remarks/>
        public string CRSem {
            get {
                return this.cRSemField;
            }
            set {
                this.cRSemField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemDCTF {
            get {
                return this.vlrCRSemDCTFField;
            }
            set {
                this.vlrCRSemDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRSemSuspDCTF {
            get {
                return this.vlrCRSemSuspDCTFField;
            }
            set {
                this.vlrCRSemSuspDCTFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.reinf.esocial.gov.br/schemas/evtRetCons/v2_01_01")]
    public partial class ReinfEvtRetConsInfoTotalCRTotApurDia {
        
        private sbyte perApurDiaField;
        
        private string cRDiaField;
        
        private string vlrCRDiaDCTFField;
        
        private string vlrCRDiaSuspDCTFField;
        
        /// <remarks/>
        public sbyte perApurDia {
            get {
                return this.perApurDiaField;
            }
            set {
                this.perApurDiaField = value;
            }
        }
        
        /// <remarks/>
        public string CRDia {
            get {
                return this.cRDiaField;
            }
            set {
                this.cRDiaField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaDCTF {
            get {
                return this.vlrCRDiaDCTFField;
            }
            set {
                this.vlrCRDiaDCTFField = value;
            }
        }
        
        /// <remarks/>
        public string vlrCRDiaSuspDCTF {
            get {
                return this.vlrCRDiaSuspDCTFField;
            }
            set {
                this.vlrCRDiaSuspDCTFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Transforms", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class TransformsType {
        
        private TransformType[] transformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transform")]
        public TransformType[] Transform {
            get {
                return this.transformField;
            }
            set {
                this.transformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class ManifestType {
        
        private ReferenceType[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ReferenceType[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureProperties", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignaturePropertiesType {
        
        private SignaturePropertyType[] signaturePropertyField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SignatureProperty")]
        public SignaturePropertyType[] SignatureProperty {
            get {
                return this.signaturePropertyField;
            }
            set {
                this.signaturePropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureProperty", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignaturePropertyType {
        
        private System.Xml.XmlElement[] itemsField;
        
        private string[] textField;
        
        private string targetField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
